### ISSUE TITLE
无法打开，出现报错

### ISSUE THREAD

**Issue by Fnlyu** [watchingfun/Joi#16]
![Quicker_20231219_224801](https://github.com/watchingfun/Joi/assets/153590199/7a799470-06c6-41b6-8038-f5e1ce97fd03)
更新c++运行库后依旧打不开

**Comment by watchingfun** [comment]
你打开终端，输入`wmic /？`  截图我看看是啥

**Comment by Fnlyu** [comment]
![tmp4443](https://github.com/watchingfun/Joi/assets/153590199/ea731943-edc5-42e9-aed8-bfb9e5c95ee3)

**Comment by Fnlyu** [comment]
你好，我找到原因了，系统环境变量出问题了，我修改好了，打扰了
