### ISSUE TITLE
需要帮助在github action上自动编译吗

### ISSUE THREAD

**Issue by AnnAngela** [watchingfun/Joi#17]
我写了个demo版本的workflow：<https://github.com/AnnAngela/Joi/blob/0a442569881faec8aba8b4a74b773a41b87caa47/.github/workflows/main.yml>

效果见：<https://github.com/AnnAngela/Joi/actions/runs/7334559750> 

可做参考

**Comment by watchingfun** [comment]
大佬，太需要了

**Comment by AnnAngela** [comment]
@watchingfun 我没太搞懂electron-builder怎么发布到release

**Comment by watchingfun** [comment]
> @watchingfun 我没太搞懂electron-builder怎么发布到release

我研究研究

**Comment by watchingfun** [comment]
感谢大佬的demo，我终于搞定了🥰
