### ISSUE TITLE
请问为什么安装exe后一直连接不上

### ISSUE THREAD

**Issue by BMQAQ** [watchingfun/Joi#25]
通过exe安装一直连接不上，尝试过管理员模式

**Comment by watchingfun** [comment]
版本号多少，发下日志

**Comment by BMQAQ** [comment]
0.5.14
[logs.zip](https://github.com/watchingfun/Joi/files/14405942/logs.zip)

**Comment by watchingfun** [comment]
有空加个群我帮你远程看看吗，我看日志显示是用户未授权

**Comment by BMQAQ** [comment]
好的，不过要明天才可以  另外我没找到群号

**Comment by watchingfun** [comment]
> 好的，不过要明天才可以  另外我没找到群号

716327527

**Comment by BMQAQ** [comment]
你好 昨晚加群一直没有通过
