### ISSUE TITLE
0.6.1安装万打开直接报错 

### ISSUE THREAD

**Issue by TonyZitwasstanned** [watchingfun/Joi#26]
0.6.1安装万打开直接报错

**Comment by Raudience** [comment]
![image](https://github.com/watchingfun/Joi/assets/52769726/8853789e-f34f-4bb1-bd70-5841bdbe8887)
ge
跟我这个一样的报错吗，上个版本使用正常，更新后报错

**Comment by watchingfun** [comment]
已更新，重新下载
