### ISSUE TITLE
催更！

### ISSUE THREAD

**Issue by gonfei** [watchingfun/Joi#36]

**Comment by qiu5225** [comment]
Auto-ban and auto-pick is hoped been added!

**Comment by gonfei** [comment]
> Auto-ban and auto-pick is hoped been added!

蟹蟹作者的辛苦付出，我有个提议。

自动跳过对局，需要跳过点赞吧。我每次跳过对局都会卡那。我也尝试过其他软件，发现他们都加入的有跳过点赞、跳过对局。

希望能做一下调整
